"""Add 'is_rws' field to OAuth clients.

Revision ID: 19d093e10169
Revises: f0fdadd25eeb
Create Date: 2019-08-23 07:02:09.613328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d093e10169'
down_revision = 'f0fdadd25eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('is_rws', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'is_rws')
    # ### end Alembic commands ###
