"""Add groups array to User

Revision ID: 3ebafc557e02
Revises: 29e40065e295
Create Date: 2026-02-26 11:30:18.088070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ebafc557e02'
down_revision = '29e40065e295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('groups', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.execute("UPDATE users SET groups = ARRAY['wizard'] WHERE is_wizard = true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'groups')
    # ### end Alembic commands ###
