"""Add audio debug mode column

Revision ID: db101a8f656f
Revises: 19d093e10169
Create Date: 2025-03-24 02:08:48.539910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db101a8f656f'
down_revision = '19d093e10169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('audio_debug_mode', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'audio_debug_mode')
    # ### end Alembic commands ###
