"""empty message

Revision ID: f0fdadd25eeb
Revises: df479ebe183f
Create Date: 2019-08-10 06:33:22.138914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0fdadd25eeb'
down_revision = 'df479ebe183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('boot_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boot_overrides')
    # ### end Alembic commands ###
